# Generated by Django 3.1 on 2020-12-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creat1',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='creat2',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='creat3',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='fromuser1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='fromuser2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='fromuser3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='imgf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1', models.CharField(max_length=100)),
            ],
        ),
    ]
