# Generated by Django 3.1 on 2020-12-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1', models.ImageField(upload_to='')),
                ('section2', models.ImageField(upload_to='')),
                ('section3', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='imgf',
        ),
    ]
