# Generated by Django 3.1 on 2020-12-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanar', '0002_auto_20201216_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='section1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='img',
            name='section2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='img',
            name='section3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
