# Generated by Django 3.1 on 2020-12-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanar', '0003_auto_20201216_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='img1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='img2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section2', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='img3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section3', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='img',
        ),
    ]
